In [19]:
'''
6) NLA.8.2
7) Check the matrix given
'''
import numpy as np
from numpy import linalg

def mgs(A):
    '''
    :param A: m x n matrix
    :return:   Q: m x n matriax with orthonormal columns
               R: n x n triangular matrix
    '''
    Q = A.copy().astype('float32')   # let q_i overwrite v_i
    nRow = A.shape[0]
    nCol = A.shape[1]
    R = np.zeros((nCol, nCol), dtype='float32')
    # Q = np.zeros((nRow, nCol), dtype='float32')
    for i in range(nCol):
        R[i,i] = linalg.norm(Q[:,i])
        Q[:,i] /= R[i,i]
        for j in range(i+1, nCol):
            R[i,j] = Q[:,i].T @ Q[:,j]
            Q[:,j] -= R[i,j] * Q[:,i]
    return Q,R


In [20]:

# check orthogonality
A = np.array(((0.70000,0.70711), (0.70001, 0.70711)), dtype='float32')
Q,R = mgs(A)
print('Q: \n', Q)
print('R: \n', R)
normQ = linalg.norm(Q.T @Q - np.eye(2))
print('norm from my function:', normQ)

Q2,R2 = linalg.qr(A)
normQ2 = linalg.norm(Q2.T @Q2 - np.eye(2))
print('norm from linalg.qr: ', normQ2)

Q: 
 [[ 0.7071017   0.70710677]
 [ 0.70711184 -0.70710677]]
R: 
 [[9.8995656e-01 1.0000045e+00]
 [0.0000000e+00 7.1649642e-06]]
norm from my function: 1.0142310648457003e-05
norm from linalg.qr:  6.22365292450572e-08


In [28]:
'''
9)

'''
import numpy as np
from numpy import linalg



def house(A):
    nRow = A.shape[0]
    nCol = A.shape[1]
    A_ = A.copy()
    vk = np.zeros((nRow, nCol))
    for k in range(nCol):
        x = A[k:nRow, k]
        e1 = np.zeros_like(x)
        e1[0] = 1
        vector = linalg.norm(x)*e1
        if x[0]  < 0:
            vector = -vector
        v =  vector + x
        v =  v/ linalg.norm(v)
        vk[k:,k] = v
        A_[k:nRow, k:nCol] =  A_[k:nRow, k:nCol] - 2*(v.reshape(-1,1))@(v.T@ A_[k:nRow, k:nCol]).reshape(1,-1)
    return vk, A_





In [ ]:

def formQ(W):
    Q = np.zeros((nRow, nRow))
    nRow = A.shape[0]
    nCol = W.shape[1]
    for k in range(nCol):
        v = W[:,k]
        size_v = v.shape[0]
        Hbar = np.identity(size_v) - ((2 * np.matmul(np.transpose(v), v)) / np.matmul(v, np.transpose(v)))
        H = np.identity(nRow)
        H[k:,k:]= Hbar
    return Q


In [33]:
'''
10)
'''
Z = np.array(((1,2,3),(4,5,6),(7,8,7),(4,2,3),(4,2,2)))
print(Z)

[[1 2 3]
 [4 5 6]
 [7 8 7]
 [4 2 3]
 [4 2 2]]


In [34]:
Q,R = mgs(A)
print('Q: \n', Q)
print('R: \n', R)

Q: 
 [[ 0.7071017   0.70710677]
 [ 0.70711184 -0.70710677]]
R: 
 [[9.8995656e-01 1.0000045e+00]
 [0.0000000e+00 7.1649642e-06]]


In [36]:
W, R = house(A)
print('W: \n',W)
print('R: \n', R)

W: 
 [[0.92387819 0.        ]
 [0.38268673 1.        ]]
R: 
 [[-9.8995668e-01 -1.0000045e+00]
 [-5.9604645e-08  7.1525574e-06]]
